/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("fr.arsenelapostolet.fsa_banking_system.kotlin-application-conventions")
    id("io.ktor.plugin") version "2.3.2"
}

dependencies {
    implementation(project(":core"))
}

application {
    // Define the main class for the application.
    mainClass.set("fr.arsenelapostolet.fsa_banking_system.app.AppKt")
    val isDevelopment: Boolean = project.ext.has("development")
    applicationDefaultJvmArgs = listOf("-Dio.ktor.development=$isDevelopment")
}


dependencies {
    implementation("io.ktor:ktor-server-core-jvm:2.3.2")
    implementation("io.ktor:ktor-server-netty-jvm:2.3.2")
    implementation("ch.qos.logback:logback-classic:1.2.11")
    testImplementation("io.ktor:ktor-server-tests-jvm:2.3.2")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.9.0")
}